### PR TITLE
Added sideways movement code

### LINKED ISSUE #61: MoveSideways()

### PR DESCRIPTION
**Pull request by Robear2100**

### CODE REVIEW

**Review by jdelim — CHANGES_REQUESTED** [review]
missing ; in line 45

**Comment by jdelim** [comment]
requested fix to syntax error (missing ;), PR waiting for dr webster approval

**Comment by Robear2100** [comment]
oops.

**Review by jdelim — APPROVED** [review]
syntax error fixed, any other errors will be looked at in hotfix

**Pull request merged**
